name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
            sudo apt install libsdl2-dev libflac-dev libvpx-dev 
    - name: make
      run: make
    - name: Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: eduke32
        path: |
            ./eduke32 ./mapster32
